### PR TITLE
Replace all usages of | in type strings for Python 3.9 compat

### LINKED ISSUE #1831: systembridgecli: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
### Description

Running the example `python -m systembridgecli --help` (though on my system I use `python3`) I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/scott/.local/lib/python3.9/site-packages/systembridgecli/__main__.py", line 151, in <module>
    app()
  File "/home/scott/.local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/scott/.local/lib/python3.9/site-packages/typer/main.py", line 232, in get_command
    click_command = get_group(typer_instance)
  File "/home/scott/.local/lib/python3.9/site-packages/typer/main.py", line 218, in get_group
    group = get_group_from_info(TyperInfo(typer_instance))
  File "/home/scott/.local/lib/python3.9/site-packages/typer/main.py", line 349, in get_group_from_info
    command = get_command_from_info(command_info=command_info)
  File "/home/scott/.local/lib/python3.9/site-packages/typer/main.py", line 425, in get_command_from_info
    ) = get_params_convertors_ctx_param_name_from_function(command_info.callback)
  File "/home/scott/.local/lib/python3.9/site-packages/typer/main.py", line 401, in get_params_convertors_ctx_param_name_from_function
    parameters = get_params_from_function(callback)
  File "/home/scott/.local/lib/python3.9/site-packages/typer/utils.py", line 11, in get_params_from_function
    type_hints = get_type_hints(func)
  File "/usr/lib/python3.9/typing.py", line 1449, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/lib/python3.9/typing.py", line 283, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/lib/python3.9/typing.py", line 539, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

### What Platform / OS are you running?

Linux

### What version are you running?

3.3.0

### Anything in the logs or a references that might be useful?

It's not entirely clear to me if `systembridgebackend` needs to be running for the CLI tool to work. It is running via `python3 -m systembridgebackend --no-gui`, but there are some errors. Here's an example of one:

```
2022-07-06 12:24:38 ERROR (Thread-12) [systembridgeshared.database.Database] Error executing SQL: INSERT INTO disk (key, value, timestamp) VALUES ('io_counters_read_count', '992937', 1657124678.8771517) ON CONFLICT(key) DO UPDATE SET value = '992937', timestamp = 1657124678.8771517 WHERE key = 'io_counters_read_count'
cannot commit - no transaction is active
```

All of them seem to be SQL related errors. I can create a separate issue for these errors if it seems unrelated.

### Additional information

Full version information:

```
$ python3 -m pip show systembridgeshared systembridgebackend systembridgecli systembridgefrontend systembridgegui
Name: systembridgeshared
Version: 3.3.0
Summary: System Bridge Shared
Home-page: https://github.com/timmo001/system-bridge
Author: Aidan Timson (Timmo)
Author-email: contact@timmo.xyz
License: MIT
Location: /home/scott/.local/lib/python3.9/site-packages
Requires: aiohttp, appdirs, colorlog, cryptography, incremental, pandas, pydantic
Required-by:
---
Name: systembridgebackend
Version: 3.3.0
Summary: System Bridge Backend
Home-page: https://github.com/timmo001/system-bridge
Author: Aidan Timson (Timmo)
Author-email: contact@timmo.xyz
License: MIT
Location: /home/scott/.local/lib/python3.9/site-packages
Requires: aiogithubapi, incremental, keyboard, mutagen, plyer, psutil, pyinstaller, sanic, sanic-ext, sanic-scheduler, zeroconf
Required-by:
---
Name: systembridgecli
Version: 3.3.0
Summary: System Bridge CLI
Home-page: https://github.com/timmo001/system-bridge
Author: Aidan Timson (Timmo)
Author-email: contact@timmo.xyz
License: MIT
Location: /home/scott/.local/lib/python3.9/site-packages
Requires: incremental, pyinstaller, shellingham, tabulate, typer
Required-by:
---
Name: systembridgefrontend
Version: 3.3.0
Summary: System Bridge Frontend
Home-page: https://github.com/timmo001/system-bridge
Author: Aidan Timson (Timmo)
Author-email: contact@timmo.xyz
License: MIT
Location: /home/scott/.local/lib/python3.9/site-packages
Requires:
Required-by:
---
Name: systembridgegui
Version: 3.3.0
Summary: System Bridge GUI
Home-page: https://github.com/timmo001/system-bridge
Author: Aidan Timson (Timmo)
Author-email: contact@timmo.xyz
License: MIT
Location: /home/scott/.local/lib/python3.9/site-packages
Requires: incremental, pyinstaller, pyperclip, PySide6, typer
Required-by:
```

System info:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute

$ uname -a
Linux scott-desktop-linux 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by rpavlik**
# Proposed Changes

Modified all type annotations that used |. Most could be replaced by Optional[], while a few actually needed Union[]. Use of | is Python 3.10+ only, which is not widely used yet. e.g. the latest stable Debian is on 3.9.

## Related Issues

Fixes #1831

At least the first part of it, for me.

## Checklist

- [x] Change has been tested and works on my device(s).

### CODE REVIEW

**Comment by rpavlik** [comment]
Looks like the CI failures are spurious git errors, but I don't have permission to retry them.

**Comment by rpavlik** [comment]
Rebased, fixed conflicts/new issues.

We should probably have CI run some tests on Python 3.9 otherwise it will be too easy to have something 3.9-incompatible sneak in again.

**Comment by rpavlik** [comment]
I think there's something wrong with your workflows, all the Black jobs work fine but the others error out when trying to clone from Git. I wonder if it's not handling the fact that I have a fork of the repo, instead of pushing to the origin.

**Comment by ScottG489** [comment]
@timmo001 Have you had a chance to take a look at this?

**Review by timmo001 — APPROVED** [review]
This looks fine.

I'm not sure what the pipelines are doing. They work for me and dependabot so its strange they aren't playing ball here.

**Comment by ScottG489** [comment]
Confirmed version `3.4.3` has fixed this specific error for me. Thanks @rpavlik!

**Pull request merged**
